name: Publish to npm

on:
  release:
    types:
      - published

jobs:
  publish:
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: pnpm -r version ${{ github.event.release.tag_name }} --no-git-tag-version
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build
      - run: pnpm -r publish --provenance --access public
